[package]
name = "git-blame"
version = "0.1.0"
edition = "2024"

[lib]
name = "git_blame"
crate-type = ["cdylib"]

[dependencies]
abi_stable = "0.11.3"
gix = { version = "0.87.1", default-features = false, features = ["sha1", "blame", "parallel"] }
jiff = "0.2.35"
steel-core = { version = "0.8.2", features = ["dylibs", "sync"] }
